congreso/urls.py
from django.conf import settings
from django.urls import path, include
# from django.conf.urls import url, include, path
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include("registro.urls")),
    path('login/', auth_views.login, name="login"),
	path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'), 
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registro/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
	
	path('', views.index, name="index"),	
	path('confirmacion/', views.confirmacion, name="confirmacion"),
	
	path('pagos/', views.pagos, name="pagos"),
	path('pagos/print/', views.pagos_print, name="pagos_print"),

	path('horarios/', views.horarios, name="horarios"),	
	path('resumen/', views.resumen, name="resumen"),	

	# path('horarios/<int:lugar_id>', views.horarios, name="horarios"),
	
	path('registros/pago/<int:id>', views.registros_pago, name="registros_pago"),
	path('registros/', views.registros, name="registros"),
	path('registros/print/', views.registros_print, name="registros_print"),
	path('registros/nuevo', views.registros_nuevo, name="registros_nuevo"),
	path('registros/editar/<int:id>', views.registros_editar, name="registros_editar"),
	
	path('ponentes/', views.ponentes, name="ponentes"),
	path('ponentes/nuevo/', views.ponentes_nuevo, name="ponentes_nuevo"),
	path('ponentes/editar/<int:id>', views.ponentes_editar, name="ponentes_editar"),
	path('ponentes/detalle/<int:id>', views.ponentes_detalle, name="ponentes_detalle"),
	
	# path('profesores/', views.profesores, name="profesores"),
	# path('profesores/nuevo/', views.profesores_nuevo, name="profesores_nuevo"),
	# path('profesores/editar/<int:id>', views.profesores_editar, name="profesores_editar"),
	# path('profesores/detalle/<int:id>', views.profesores_detalle, name="profesores_detalle"),
	
	# path('conferencias/', views.conferencias, name="conferencias"),
	# path('conferencias/nuevo/', views.conferencias_nuevo, name="conferencias_nuevo"),
	# path('conferencias/editar/<int:id>', views.conferencias_editar, name="conferencias_editar"),
	
	path('talleres/', views.talleres, name="talleres"),
	path('talleres/nuevo/', views.talleres_nuevo, name="talleres_nuevo"),
	path('talleres/editar/<int:id>', views.talleres_editar, name="talleres_editar"),
	
	# path('lugares/', views.lugares, name="lugares"),
	# path('lugares/nuevo/', views.lugares_nuevo, name="lugares_nuevo"),
	# path('lugares/editar/<int:id>', views.lugares_editar, name="lugares_editar"),
	
]

registro/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Lugar(models.Model):
	nombre = models.CharField(max_length=255)

	def __str__(self):
		return self.nombre

class Horario(models.Model):
	
	user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)	
	# lugar = models.ForeignKey(Lugar, on_delete=models.CASCADE)
	sala = models.CharField(max_length=255)
	fecha = models.DateField()
	dia = models.CharField(max_length=10, choices=[("Dom", "Domingo"),
		("Lun", "Lunes"),
		("Mar", "Martes"),
		("Mie", "Miercoles"),
		("Jue", "Jueves"),
		("Vie", "Viernes"),
		("Sab", "Sabado")], default="Mie")
	hora = models.TimeField()
	hora_fin = models.TimeField()

	def __str__(self):
		return self.sala + " " + str(self.dia) + " " + str(self.fecha) + " " + str(self.hora) + " - " + str(self.hora_fin)

class Ponente(models.Model):

	TIPOS = [
		("ponente", "Ponente"),
		("profesor", "Profesor"),
	]

	CARRERAS = [
		("arquitectura", "Arquitectura"),
		("bioquimica", "Ingeniería Bioquímica"),
		("electromecanica", "Ingeniería Electromecánica"),
		("sistemas", "Ingeniería en Sistemas Computacionales"),
		("gestion", "Ingenieria en Gestión Empresarial"),
		("administracion", "Licenciatura en Administración"),
		("contabilidad", "Contador Público"),
	]

	fecha_registro = models.DateField(auto_now_add=True)
	fecha_modificacion = models.DateField(auto_now=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	
	ponencia = models.CharField(max_length=255)		
	horario = models.ForeignKey(Horario, on_delete=models.SET_NULL, null=True)
	foto_ponencia = models.ImageField(blank=True, null=True)
	carrera = models.CharField(max_length=255, choices=CARRERAS)	

	nombre = models.CharField(max_length=255)
	email = models.EmailField(max_length=255)
	telefono = models.CharField(max_length=20)
	titulo = models.CharField(max_length=50)
	resumen = models.CharField(max_length=255)
	intro = models.TextField()
	foto = models.ImageField(blank=True)
	activo = models.BooleanField()
	tipo = models.CharField(max_length=255, choices=TIPOS, default="ponente")

	def __str__(self):
		return self.titulo + " " + self.nombre

# class Profesor(models.Model):
# 	nombre = models.CharField(max_length=255)
# 	email = models.EmailField(max_length=255, null=True, blank=True)
# 	telefono = models.CharField(max_length=20, null=True, blank=True)

# 	def __str__(self):
# 		return self.nombre


class Conferencia(models.Model):

	CARRERAS = [
		("arquitectura", "Arquitectura"),
		("bioquimica", "Ingeniería Bioquímica"),
		("electromecanica", "Ingeniería Electromecánica"),
		("sistemas", "Ingeniería en Sistemas Computacionales"),
		("gestion", "Ingenieria en Gestión Empresarial"),
		("administracion", "Licenciatura en Administración"),
		("contabilidad", "Contador Público"),
	]

	fecha_registro = models.DateField(auto_now_add=True)
	fecha_modificacion = models.DateField(auto_now=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	nombre = models.CharField(max_length=255)	
	requisitos = models.CharField(max_length=255, blank=True, null=True)
	objetivo = models.TextField()
	descripcion = models.TextField()
	ponente = models.ForeignKey(Ponente, models.CASCADE, null=True)
	lugar = models.ForeignKey(Lugar, models.CASCADE, null=True)
	sala = models.CharField(max_length=255, null=True)
	fecha_hora = models.DateField()	
	duracion = models.IntegerField()
	fecha_fin = models.DateField()
	hora = models.TimeField()	
	hora_fin = models.TimeField()
	carrera = models.CharField(max_length=255, choices=CARRERAS)	
	foto = models.ImageField(blank=True, null=True)
	tipo = models.CharField(max_length=20, choices=[("conferencia", "Conferencia"), ("taller", "Taller")])	
	horario = models.ForeignKey(Horario, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.nombre

class Taller(models.Model):

	CARRERAS = [
		("arquitectura", "Arquitectura"),
		("bioquimica", "Ingeniería Bioquímica"),
		("electromecanica", "Ingeniería Electromecánica"),
		("sistemas", "Ingeniería en Sistemas Computacionales"),
		("gestion", "Ingenieria en Gestión Empresarial"),
		("administracion", "Licenciatura en Administración"),
		("contabilidad", "Contador Público"),
	]

	fecha_registro = models.DateField(auto_now_add=True)
	fecha_modificacion = models.DateField(auto_now=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	
	nombre = models.CharField(max_length=255)	
	profesor = models.CharField(max_length=255)
	salon = models.CharField(max_length=255)
	fecha = models.DateField()	
	fecha_fin = models.DateField()
	duracion = models.IntegerField()
	hora = models.TimeField()	
	hora_fin = models.TimeField()
	objetivo = models.CharField(max_length=255)
	
	requisitos = models.CharField(max_length=255, blank=True, null=True)
	descripcion = models.TextField(null=True, blank=True)
	
	carrera = models.CharField(max_length=255, choices=CARRERAS)	
	foto = models.ImageField(blank=True, null=True)	

	def __str__(self):
		return self.nombre

class Registro(models.Model):

	TIPO_REGISTRO = [
		('alumno', 'Alumno del ITA'),
		('exalumno', 'Exalumno del ITA'),
		('alumno2', 'Alumno de otra institución'),
		('profesional', 'Profesionista')
	]

	ESTADOS = [
		("AGU","Aguascalientes"),
		("BCN","Baja California"),
		("BCS","Baja California Sur"),
		("CAM","Campeche"),
		("CHH","Chihuahua"),
		("CHP","Chiapas"),
		("COA","Coahuila"),
		("COL","Colima"),
		("DIF","Ciudad de México"),
		("DUR","Durango"),
		("GRO","Guerrero"),
		("GUA","Guanajuato"),
		("HID","Hidalgo"),
		("JAL","Jalisco"),
		("MEX","México"),
		("MIC","Michoacán"),
		("MOR","Morelos"),
		("NAY","Nayarit"),
		("NLE","Nuevo León"),
		("OAX","Oaxaca"),
		("PUE","Puebla"),
		("QUE","Querétaro"),
		("ROO","Quintana Roo"),
		("SIN","Sinaloa"),
		("SLP","San Luis Potosí"),
		("SON","Sonora"),
		("TAB","Tabasco"),
		("TAM","Tamaulipas"),
		("TLA","Tlaxcala"),
		("VER","Veracruz"),
		("YUC","Yucatán"),
		("ZAC","Zacatecas"),
	]

	CARRERAS = [
		("sistemas", "Ingeniería en Sistemas Computacionales"),
		("bioquimica", "Ingeniería Bioquímica"),
		("electromecanica", "Ingeniería Electromecánica"),
		("arquitectura", "Arquitectura"),
		("administracion", "Licenciatura en Administración"),
		("contabilidad", "Contador Público"),
		("gestion", "Ingenieria en Gestión Empresarial"),
		("otra", "Otra Institución"),
		("profesionista", "Profesionista"),
	]

	SEMESTRES = [
		("1", "1"),
		("2", "2"),
		("3", "3"),
		("4", "4"),
		("5", "5"),
		("6", "6"),
		("7", "7"),
		("8", "8"),
		("9", "9"),
		("10", "10"),
		("11", "11"),
		("12", "12")		
	]

	STATES = [
		("draft", "Nuevo"),
		("open", "Confirmado"),
		("done", "Pagado")
	]

	GENERO = [
		("hombre", "Hombre"),
		("mujer", "Mujer"),		
	]

	fecha_registro = models.DateField(auto_now_add=True)
	fecha_modificacion = models.DateField(auto_now=True)
	fecha_pago = models.DateField(null=True, blank=True)
	# user = models.ForeignKey(User, on_delete=models.CASCADE)
	nombre = models.CharField(max_length=255)
	apellidop = models.CharField(max_length=255)
	apellidom = models.CharField(max_length=255)
	nocontrol = models.CharField(max_length=255, null=True, blank=True)
	rfc = models.CharField(max_length=255, null=True, blank=True)
	institucion = models.CharField(max_length=255)
	carrera = models.CharField(max_length=255, choices=CARRERAS, null=True, blank=True)
	semestre = models.CharField(max_length=255, choices=SEMESTRES, null=True, blank=True)
	email = models.EmailField(max_length=255)
	telefono = models.CharField(max_length=10)
	municipio = models.CharField(max_length=255)	
	estado = models.CharField(max_length=255, choices=ESTADOS)
	tipo_registro = models.CharField(max_length=255, choices=TIPO_REGISTRO)
	saldo = models.DecimalField(max_digits=6, decimal_places=2, default=0)
	pagado = models.DecimalField(max_digits=6, decimal_places=2, default=0)
	state = models.CharField(max_length=255, choices=STATES)
	genero = models.CharField(max_length=10, choices=GENERO)

	def __str__(self):
		return self.nombre

registro/forms.py
from django import forms
from django.forms import ModelForm, NumberInput, TextInput, Textarea

from .models import Registro, Ponente, Conferencia, Lugar, Horario, Taller

class PonenteModelForm(ModelForm):

	class Meta:
		model = Ponente
		labels = {
			'horario' : 'Lugar y Fecha',					
		}
		fields = ("ponencia", "horario", "titulo", "nombre", "email", "telefono", "resumen", "activo", "intro")

	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user')
		super(PonenteModelForm, self).__init__(*args, **kwargs)
		self.fields['horario'].queryset = Horario.objects.filter(user__exact=user).order_by('sala', 'fecha', 'hora')


class LugarModelForm(ModelForm):

	class Meta:
		model = Lugar
		fields = '__all__'

class HorarioModelForm(ModelForm):

	class Meta:
		model = Horario
		fields = '__all__'

class ConferenciaModelForm(ModelForm):

	class Meta:
		model = Conferencia
		labels = {
			'nombre' : 'Titulo',
			'duracion' : 'Duración (Horas)',
			'fecha_hora' : 'Fecha',
			'hora' : 'Hora de Inicio',
			'hora_fin' : 'Hora de Término',			
		}
		fields = ("nombre", "ponente", "lugar", "horario", "fecha_hora", "hora", "hora_fin", "foto", "descripcion")

	def __init__(self, *args, **kwargs):
		super(ConferenciaModelForm, self).__init__(*args, **kwargs)
		self.fields['ponente'].queryset = Ponente.objects.filter(tipo__exact="ponente")

class TallerModelForm(ModelForm):

	class Meta:
		model = Taller
		labels = {
			'nombre' : 'Nombre del Taller',			
			'fecha' : 'Fecha de Inicio',
			'duracion' : 'Duración (Dias)',
			'hora' : 'Hora de Inicio',
			'hora_fin' : 'Hora de Termino',
			'profesor' : 'Instructor',
			'requisitos' : 'Requisitos del Participante',
			'descripcion' : 'Programa'
		}
		fields = ("nombre", "profesor", "salon", "fecha", "duracion", "hora", "hora_fin",  "requisitos", "foto", "objetivo", "descripcion")
	# def __init__(self, *args, **kwargs):
	# 	super(TallerModelForm, self).__init__(*args, **kwargs)
	# 	self.fields['ponente'].queryset = Ponente.objects.filter(tipo__exact="profesor")

class RegistroModelForm(ModelForm):

	# rfc = forms.CharField(required=False)
	# nocontrol = forms.CharField(required=False)

	class Meta:
		model = Registro
		fields = ("tipo_registro", "nombre", "apellidop", "apellidom", "genero", "nocontrol", "rfc", "institucion", "carrera", "semestre", "email", "telefono", "municipio", "estado")
		# fields = "__all__" #("precio",)
		# exlude = ("imagen",)
		labels = {
			'nombre' : 'Nombre(s)*',
			'apellidop' : 'Apellido Paterno*',
			'apellidom' : 'Apellido Materno*',
			'nocontrol' : 'Matrícula o No. de Control*',
			'rfc' : 'RFC*',
			'telefono' : 'Teléfono (con Clave Lada)',
			'institucion' : 'Empresa / Institución',
			'tipo_registro' : 'Tipo de Registro*',
			'genero' : 'Genero*',
			'institucion' : 'Institución*',
			'carrera' : 'Carrera*',
			'semestre' : 'Semestre*',
			'email' : 'Email*',
			'municipio' : 'Municipio*',
			'estado' : 'Estado*'

		}
		widgets = {
			# 'descripcion' : Textarea(attrs={'cols':80, 'rows':5}),
			# 'precio': NumberInput(attrs={'min': 0}), 
			# 'cantidad': NumberInput(attrs={'min': 0}),            
		}

	def __init__(self, *args, **kwargs):
		super(RegistroModelForm, self).__init__(*args, **kwargs)
		self.fields['rfc'].required = False
		self.fields['nocontrol'].required = False
		self.fields['telefono'].required = False

registro/templates/registro/conferencias_editar.html
{% extends 'baseadmin.html' %}
{% block content %}
<section>

<div class="row">
	<div class="col text-center">
		<h1>Edición de Datos</h1>
		<hr class="divider red">
	</div>
</div>
<div class="row">
	
	<div class="col-8 offset-2">		
		
		<form action="" method="post" enctype="multipart/form-data">
		    {% csrf_token %}
		    <!-- <table>    	 -->
			<div class="row">				
		    {% for field in form %}

		    	{% if field.name == "descripcion" %}
				<div class="col-12">
					{{ field.label_tag }} 
					{{ field }}
		    		<br>
				</div>						
		    	{% else %}
				<div class="col-6">
					{{ field.label_tag }} 
					{{ field }}
		    		<br>
				</div>
		    	{% endif %}
			

		    {% endfor %}
			</div>

		    <!-- </table> -->
		    <div class="row">		    	
				<div class="col-6 offset-3">
		    		<input type="submit" class="btn btn-danger" value="Guardar" />
		    	</div>
		    </div>
		</form>
	</div>
</div>
</section>

{% endblock %}

{% block scripts %}
<script type="text/javascript">
	$("#id_fecha_hora").attr("type", "date");
	$("#id_hora, #id_hora_fin").attr("type", "time");
</script>
{% endblock %}

registro/templates/registro/conferencias_nuevo.html
{% extends 'baseadmin.html' %}

{% block content %}

<section id="registro">
	
<div class="row">
	<div class="col-8 offset-2">
		<h1 class="text-center">Conferencias</h1>
		<hr class="divider red">
	</div>
</div>

<div class="row">		
	<div class="col-10 offset-1">
		<form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<!-- <table>    	 -->
			
			<div class="row">

			{% for field in form %}			

				<div class="col-6">

					{% if field.name == 'fecha_hora' %}
					{{ field.label_tag }} 					
					<input type="date" class="form-control" name="fecha_hora" id="id_fecha_hora" value="{{ field.value }}">
					{% elif field.name == 'hora' %}
					{{ field.label_tag }} 					
					<input type="time" class="form-control" name="hora" id="id_hora" value="{{ field.value }}">
					{% elif field.name == 'descripcion' %}
					</div></div>
					<div class="row">
					<div class="col">
					{{ field.label_tag }} 					
					{{ field }}
					{% else %}
					{{ field.label_tag }} 					
					{{ field }}
					{% endif %}
					<br>
				</div>			
				
			{% endfor %}
			</div>			
		    <div class="row">		    	
				<div class="col-4 offset-4">
		    		<input type="submit" class="btn btn-lg btn-danger" value="GUARDAR" />
		    	</div>
		    </div>
		</form>			
	</div>
</div>

</section>

{% endblock %}
{% block scripts %}
<script type="text/javascript">

	$("#id_lugar").on("change", function(){
		let val = $(this).val()
		if(val != "")
		{
			$.getJSON("/horarios/" + val, function(res){
				console.log(res)

				if(res.length > 0)
				{
					let opts = ""
					$.each(res, function(idx, val){

					})
				}
			})
		}
	})

	$("#id_fecha_hora").attr("type", "date");
	$("#id_hora, #id_hora_fin").attr("type", "time");
</script>
{% endblock %}

registro/templates/registro/registros_editar.html
{% extends 'baseadmin.html' %}

{% load static %}

{% block content %}

<section id="registro">
	
<div class="row">
	<div class="col-8 offset-2">
		<h2 class="text-center">2do Congreso Internacional de Innovación, Tecnología y Sustentabilidad (CIITYS) 2018</h2>
		<h3 class="text-center text-muted">Registro</h3>
		<hr class="divider red">
	</div>
</div>

<row>	
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-danger">
        	{{ message.error }}
        </div>
    {% endfor %}
{% endif %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
</row>


<div class="row">		
	<div class="col-8 offset-2">
		<form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<!-- <table>    	 -->
			
			<div class="row">

			{% for field in form %}			

				<div class="col-6">
					{{ field.label_tag }} 
					{{ field }}
					<br>
				</div>
				
				<!-- {% if forloop.counter|divisibleby:2 %}
				</div>
				<div class="row">
				{% endif %} -->

			{% endfor %}
			</div>			
		    <div class="row">		    	
				<div class="col-4 offset-2">
		    		<input type="button" class="back btn btn-lg btn-secondary" value="REGRESAR" />
		    		{# <a href="/registros" class="btn btn-lg btn-secondary">REGRESAR</a> #}
		    	</div>
				<div class="col-4">
		    		<input type="submit" class="btn btn-lg btn-danger" value="GUARDAR CAMBIOS" />
		    	</div>
		    </div>
		</form>			
	</div>
</div>

</section>

{% endblock %}

{% block scripts %}

<script>

	$("#id_nocontrol").prop("required", false).parent(".col-6").hide();
	$("#id_rfc").prop("required", false).parent(".col-6").hide();

	$(".btn.back").on("click", function(e){
		e.preventDefault();
		location.href = "/registros";
	});

	function actualizar_tipo_vista()
	{
		let val = $("#id_tipo_registro").val()
		if(val == "profesional")
		{
			$("#id_rfc").prop("required", true).parent(".col-6").show();
			$("#id_nocontrol").prop("required", false).parent(".col-6").hide();			
			$("#id_institucion").prop("required", true).parent(".col-6").show();
			$("#id_carrera").prop("required", false).parent(".col-6").hide();
			$("#id_semestre").prop("required", false).parent(".col-6").hide();
		}
		else
		{
			if(val == "alumno" || val == "alumno2" )
			{
				$("#id_semestre").prop("required", true).parent(".col-6").show();
			}

			if(val == "alumno" || val == "exalumno" )
			{	
				$("#id_institucion").val("ITA")
				$("#id_institucion").prop("required", false).parent(".col-6").hide()

				$("#id_carrera").prop("required", true).parent(".col-6").show();
			}
			else //alumno otra institucion
			{				
				$("#id_institucion").prop("required", true).parent(".col-6").show();

				$("#id_carrera").prop("required", false).parent(".col-6").hide();
			}

			if (val == "exalumno")
			{
				$("#id_rfc").prop("required", false).parent(".col-6").show();				
			}
			else
			{
				$("#id_rfc").prop("required", false).parent(".col-6").hide();
			}

			$("#id_nocontrol").prop("required", true).parent(".col-6").show();
		}
	};

	actualizar_tipo_vista();

	$("#id_tipo_registro").on("change", function(){
		// alert($(this).val())
		$("#id_institucion").val("")
		actualizar_tipo_vista();
	});
	
	$(".registro").on("click", function(e){
		e.preventDefault();
		lity("/registrar/")
	});

</script>

{% endblock %}

registro/templates/registro/registros_nuevo.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}

<style>

section#registro
{
	/*background-color: #1e4e6b;
	color: white;*/
}

</style>

{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}

<section id="registro">
	
<div class="row">
	<div class="col-8 offset-2">
		<h2 class="text-center">2do Congreso Internacional de Innovación, Tecnología y Sustentabilidad (CIITYS) 2018</h2>
		<h3 class="text-center text-muted">Registro</h3>
		<hr class="divider red">
	</div>
</div>

<row>	
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-danger">
        	{{ message.error }}
        </div>
    {% endfor %}
{% endif %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
</row>


<div class="row">		
	<div class="col-8 offset-2">
		<form action="" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<!-- <table>    	 -->
			
			<div class="row">

			{% for field in form %}			

				<div class="col-6">
					{{ field.label_tag }} 
					{{ field }}
					<br>
				</div>
				
				<!-- {% if forloop.counter|divisibleby:2 %}
				</div>
				<div class="row">
				{% endif %} -->

			{% endfor %}
			* Datos Obligatorios
			</div>			
			<br>
		    <div class="row">		    	
				<div class="col-4 offset-2">
					{% if user.is_authenticated %}
		    		<input type="button" class="back btn btn-lg btn-secondary" value="SALIR" />
		    		{% else %}
		    		<input type="button" class="exit btn btn-lg btn-secondary" value="SALIR" />
					{% endif %}
		    	</div>
				<div class="col-4">
		    		<input type="submit" class="btn btn-lg btn-danger" value="REGISTRARSE" />
		    	</div>
		    </div>
		</form>			
	</div>
</div>


</section>

{% endblock %}

{% block scripts %}

<script>

	$("#id_nocontrol").prop("required", false).parent(".col-6").hide();
	$("#id_rfc").prop("required", false).parent(".col-6").hide();

	$(".btn.exit").on("click", function(e){
		e.preventDefault();
		window.close()
	});

	$(".btn.back").on("click", function(e){
		e.preventDefault();
		location.href = "/registros";
	});

	function actualizar_tipo_vista()
	{
		let val = $("#id_tipo_registro").val()
		if(val == "profesional")
		{
			$("#id_rfc").prop("required", true).parent(".col-6").show();
			$("#id_nocontrol").prop("required", false).parent(".col-6").hide();			
			$("#id_institucion").prop("required", true).parent(".col-6").show();
			$("#id_carrera").prop("required", false).parent(".col-6").hide();
			$("#id_semestre").prop("required", false).parent(".col-6").hide();
		}
		else
		{
			if(val == "alumno" || val == "alumno2" )
			{
				$("#id_semestre").prop("required", true).parent(".col-6").show();
			}

			if(val == "alumno" || val == "exalumno" )
			{	
				$("#id_institucion").val("ITA")
				$("#id_institucion").prop("required", false).parent(".col-6").hide()

				$("#id_carrera").prop("required", true).parent(".col-6").show();
			}
			else //alumno otra institucion
			{				
				$("#id_institucion").prop("required", true).parent(".col-6").show();

				$("#id_carrera").prop("required", false).parent(".col-6").hide();
			}

			if (val == "exalumno")
			{
				$("#id_rfc").prop("required", false).parent(".col-6").show();				
			}
			else
			{
				$("#id_rfc").prop("required", false).parent(".col-6").hide();
			}

			$("#id_nocontrol").prop("required", true).parent(".col-6").show();
		}
	};

	actualizar_tipo_vista();

	$("#id_tipo_registro").on("change", function(){
		// alert($(this).val())
		$("#id_institucion").val("")
		actualizar_tipo_vista();
	});
	
	$(".registro").on("click", function(e){
		e.preventDefault();
		lity("/registrar/")
	});

</script>

{% endblock %}